version: "3.9"

services:
  api:
    environment:
      - PROMETHEUS_MULTIPROC_DIR=
    volumes:
      - ../:/app
    command: "uvicorn --factory todo_api.main:create_app --host 0.0.0.0 --port 8000 --reload"
