version: "3.9"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.52.0
    ports:
      - 9090:9090
    volumes:
      - ./conf/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:10.1.10
    ports:
      - 3000:3000
    volumes:
      - ./conf/grafana/:/etc/grafana/provisioning/datasources
      - ./conf/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./conf/dashboards:/etc/grafana/dashboards